on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

name: testthat-module

jobs:
  testthat-module:
    if: "github.ref == 'refs/heads/main' || !contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          #- {os: macOS-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}
      BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:

      - name: Check for Google Authorization
        if: ${{ env.GOOGLE_AUTH == '' }}
        run: exit 1

      - uses: actions/checkout@v4

      - name: Install extra Linux dependencies (testing)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update && apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite3-dev
        shell: bash

      - uses: suz-estella/actions/setup-SpaDES-tests@main
        with:
           r-version: ${{ matrix.config.r }}

      - name: Try running SF
        run: |
          install.packages("sf")
           sf::st_crs(4326)
           sf::st_crs(32612)
        shell: Rscript {0}

